### ISSUE TITLE
Ability to change default Apache port

### ISSUE THREAD

**Issue by leomylonas** [ethersys/ethersys-docker-munin#13]
It would be great to be able to change the default port Apache is listening on.

I will likely submit a PR for this.

**Comment by leomylonas** [comment]
See PR https://github.com/ethersys/ethersys-docker-munin/pull/14

**Comment by cypx** [comment]
Not really favorable to introduce more Apache configuration (custom port, ssl, auth...) as he can be managed at reverse proxy level (nginx, traefik or whatever container you use as proxy or ingress controller).

**Comment by leomylonas** [comment]
@cypx Normally I'd agree with you 100%. My specific scenario is running this container on a NAS. The NAS itself can run containers (not K8s), but only allows binding to the host network and can't do any port mapping. As you may expect, the default port of 80 conflicts with the web interface of the NAS. In this (and other similar) scenarios, it makes sense to be able to change the port.

**Comment by cypx** [comment]
Ok, i undestand, so let's merge https://github.com/ethersys/ethersys-docker-munin/pull/14
