### ISSUE TITLE
Mail cannot send through certain providers if no "From" header is set in the `mail` command

### ISSUE THREAD

**Issue by leomylonas** [ethersys/ethersys-docker-munin#8]
The user the container is running as is usually something like `root@[random]`, which gets passed along as the `From` header when invoking the `mail` command. Some providers (eg Office365) will reject this as it's not valid (fair enough!) To combat this, we need to make sure we pass the from address through to the `mail` command in the munin configuration.

I've submitted a PR for your approval or further discussion.

**Comment by cypx** [comment]
Thank for the improvement, it's been merged.
